# This is a basic workflow to help you get started with Actions

name: cputemp

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
    # Install Ubuntu OS updates
    #- name: Install OS updates, security fixes etc
    #  run: |
        #echo "Installing OS updates, security fixes etc"
        #sudo apt update
        #sudo apt -y upgrade
        #sudo apt -y autoremove
    
    # Install dependancies and Nim language
    - name: Install dependencies and Ada language compiler
      run: |
        echo "Installing Ada language and dependencies..."
        sudo apt -y install gnat gprbuild git asis-programs
        echo "Installing Ada language generally used libraries..."
        sudo apt -y install libgnatcoll-gmp19 libgnatcoll-gmp18-dev \
        libgnatcoll18 libgnatcoll18-dev libaws19-dev libcurl4-openssl-dev \
        liblzma-dev libgnatcoll-iconv18-dev libgnatcoll-readline18-dev \
        libgnatcoll-sqlite18-dev
        echo "Installed versions of Ada compiler and gprbuild are:"
        gnat --version
        gnatmake --version
        gprbuild --version
        
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    # Runs a set of commands using the runners shell - include env secret key
    - name: Run a multi-line script
      #env:
      #    DSAPI: ${{ secrets.DSAPI }}
      run: |
        echo "Building the project..."
        pwd
        ls
        gprbuild -XBUILD=release
        cd bin/
        ./cputemp --version
        ./cputemp
        echo "DONE."

    # Saves built file as a release.
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: release
        path: bin
